server:
  servlet:
    context-path: /api
  port: 8080

spring:
  application:
    name: backend
    timezone: "Europe/Tallinn"
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: validate